---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kin-keeper-encryption-key
  namespace: homelab
spec:
  encryptedData:
    KINKEEPER_ENCRYPTION_KEY: AgCTHjRwHjNhojjWRE47Ues/aSg65mPBCiHRfwyck1hMEA699mjmyuwJojxWLUdQamNvgvmtGBO8ztehqzO0sDcEuhIJAGT8lOJXE14XaWXvYvDJWd3koLNJocG1AEU7k5GSf0VxmhzhCiw1Cn0YzsAMhTqe8Umg4kSHnkDJVgxIBSx1+eK97TqqGhiEjFoaN5hjjeSLhNyzUmasPoI9HEvp8egIHpXd1WDMZVZxR8yR9sNmXld5m++4lZG6m6GJPylus/Ao4AtqCxehYJdGpWDgTNFx1k+6YhoV/wtaWXrnjoQRgp8a8oSjfy7QN0QPCHLfB4//kwz2I1QGzV8aIXfs8+qm+QqAbzUc1rViOOW+kVUJW+96hl/4l/Ua07uABtMYVtZw57kWOS/AS5MW5OI8nx0YRdyxuFMriE63ch963YVHL40c5F/5GPVACcb7AoQDFt9CwCJZ6L94UoemY1qD5wGqkObrOej1YVn7szq/gvCfTajHltiFcfEdil1gy9lfkYAgi/uxJwIC+WKsB6yuCJ/s9kh5ry3G/vMLlLt7rmFfLR/gEWMfN/2VPBSkgseGT0Jvym4uekJNaDJK41w+lLq90+RFlW/JMhUayhMKRmHe2qXj2ypataFXUXTmPn9ZhaN23wn7rCtM1x7/IoQSdpNalKcqUTV4y3FhoRioGqdx1b2fYpOZzX+UBK4N18AtmHyFuyrJhzysEZrZtZIkcCV3qhvdc4h55o93KKl71FTiOINvvZtL6l+Qgw==
  template:
    metadata:
      name: kin-keeper-encryption-key
      namespace: homelab
