apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kin-keeper-ingress
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kin-keeper.homelab.local
        - ogautam-homelab.tail38d2ad.ts.net
      secretName: kin-keeper-tls
  rules:
    - host: kin-keeper.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kin-keeper-frontend
                port:
                  number: 80
    - host: ogautam-homelab.tail38d2ad.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kin-keeper-frontend
                port:
                  number: 80
